### ISSUE TITLE
Popover is shown out of screen bounds

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/Catch-em-all#92] opened 2016-10-03 11:15 UTC
The popover is not completely on the screen, but about 80% are below the shown screen (see screenshot).

I am using the current release from HockeyApp (Oct 3rd, 1:04am) which is the following commit:
Merge pull request #91 from PokemonGoers/poke-rarity (01a06cbb6e08a8028fda087ccae5fb836ef44666)

![screenshot_20161003-011050](https://cloud.githubusercontent.com/assets/11082297/19035694/5eea1f42-896b-11e6-9d96-048d89bd9ab9.png)

**Comment by sacdallago** [comment] 2016-10-05 04:42
Can you reproduce this also on web?

**Comment by AlexanderLill** [comment] 2016-10-05 11:47
It also happens when I use the Chrome browser on my android. I can't reproduce it with Chromium on my desktop though, even if I switch to the mobile view in the Developer Tools.

Not sure if this should be investigated if we replace the implementation of the popover anyway. If we want to investigate this, we would need more android users that try this.

**Comment by sacdallago** [comment] 2016-10-06 08:28
Happens on mine as well:
Note 4, un-rooted Android v6.0.1

Can try this evening on:
A Nexus 7 and a Tab S v2 8 and let you know if it's the case there as well. Seems to be Android bound

**Comment by philbu** [comment] 2016-10-07 10:36
Same on LG G4 with Android 6.0

**Comment by sacdallago** [comment] 2016-10-10 16:20
I'll add something to this:

now the button gets hidden by the tile layers! Are you adding the map before or after the button? Also worth looking into the `z-index` of the button.

_Edit_: you can reproduce this by zooming in or out.

**Comment by johartl** [comment] 2016-10-10 17:14
@sacdallago The bug is caused by https://github.com/PokemonGoers/PokeMap-1/issues/35
Edit: .. was caused. It's fixed now :)

**Comment by WoH** [comment] 2016-10-10 18:00
For the builds we can fix the position, however this is just a workaround.
I'll look at this again once we are on RC0

**Comment by philbu** [comment] 2016-10-10 22:45
#108 Workaround by using modal. But there is still a bug.

**Comment by WoH** [comment] 2016-10-11 13:22
Fixed: https://github.com/PokemonGoers/Catch-em-all/commit/a3b8717f883849aa91c986c625cbeba8285b7302

**Closed as completed by WoH** 2016-10-11 13:22 UTC
Labels: bug, ui
