### ISSUE TITLE
Touch Zooming and Dragging Behavior

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#78] opened 2016-09-22 10:47 UTC
There seems to be some weird behavior in terms of zooming and dragging when running the app on Android. 
To reproduce the bug you need to continuously zoom in and out and move the map. You'll eventually find yourself at a completely different place (for instance in the middle of the ocean or close to new zealand). It may be hard to explain but this bug seems to occur consistently for the native android app. 
My first guess would be that this has something to do with the touch events and how Ionic interfers with them. I think the bug does not reproduce when running the web app within google chrome on your Android device but maybe someone else should double check that.

**Comment by AlexanderLill** [comment] 2016-09-22 10:55
Happens on Android even in the normal browser...

So I guess it is an issue with the map / position parameters or something.

(@johartl)

**Comment by johartl** [comment] 2016-09-22 11:02
Then we should test the app on other touch devices (Android tablets and Microsoft Surface) to isolate the error.

**Comment by johartl** [comment] 2016-09-22 12:24
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2

**Comment by MajorBreakfast** [comment] 2016-09-22 13:24
I renamed the issue. Chrome on Windows is also affected if you use touch.

**Comment by MajorBreakfast** [comment] 2016-09-22 14:03
New insights through some playing around:
- Only when zooming (two fingers), not when just dragging
- Pokemon layer seems to move correctly, only tiles shift
- Correct zoom behavior during zooming. Tile jump happens after I lift my fingers from the screen

**Comment by MajorBreakfast** [comment] 2016-09-22 14:20
I get the same bug in Microsoft Edge.
I cannot zoom with two fingers in Firefox (Changes page zoom level instead).

**Comment by MajorBreakfast** [comment] 2016-09-22 14:45
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2
We need a way to disable any refreshes of the displayed pokemon, so that we can differentiate between movements caused by bugs (e.g. in our css or whatever) and movements caused the update of the displayed pokemon.

**Comment by AlexanderLill** [comment] 2016-09-28 18:48
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2
are there any updates? :)

**Comment by sacdallago** [comment] 2016-10-02 08:18
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2

**Comment by philbu** [comment] 2016-10-10 22:56
Fixed by new map update

**Closed as completed by philbu** 2016-10-10 22:56 UTC
Labels: bug
